spring.application.name=store

# Bind to Cloud Run port
server.port=${PORT:8080}
server.address=0.0.0.0

# Lazy initialize beans to avoid long startup blocking Firestore
spring.main.lazy-initialization=true

# GCP Firestore
spring.cloud.gcp.project-id=iteci-c8bd4

spring.cloud.gcp.credentials.use-default-credentials=true
spring.cloud.gcp.firestore.enabled=false
spring.cloud.gcp.secretmanager.enabled=false
# Firestore settings
spring.cloud.gcp.firestore.project-id=iteci-c8bd4


# Logging
logging.level.org.springframework.security=DEBUG

# Actuator endpoints
management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=always
management.health.cloud-gcp.enabled=true